apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-java-app-catalog
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-java-app-catalog
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/serpiko2/tap-java-app-catalog
      ref:
        branch: main
